#!/usr/bin/env perl

use strict;
use warnings;
use Getopt::Std;
our ($opt_x, $opt_s, $opt_t, $opt_v);
getopts('s:tvx');

sub run {
	my $cli = shift;
	print STDERR "$cli\n "if $opt_v;
	system($cli) == 0 or die;
}

my $usage = "
=============================================================================
Spliced Alignment Bakeoff Runner

usage: $0 [options] <DNA> <GFF> <DIR> <PROGRAMS>
options:
  -s <int>  random seed
  -t        minimal testing mode
  -v        verbose output
  -x        experimental genome (not real)

DNA: path to FASTA file of reference sequence
GFF: path to GFF3 file of reference annotation
DIR: output directory
PROGRAMS: any collection of programs supported by run-aligner.py
  blat bowtie2 bwa-mem gmap hisat2 magic-blast minimap2 pblat star tophat2

examples:
  ./bakeoff -vts1 1pct.dna 1pct.gff3 build blat minimap2

=============================================================================
";

die $usage unless @ARGV > 3;
my ($src_dna, $src_gff, $dir, @program) = @ARGV;

my $dna = "genome.fa";
my $gff = "genome.gff";
my $rna = "reads.fa.gz";

# Setup

if (not -d $dir) {
	run("mkdir $dir");
	run("cp $src_dna $dir/$dna");
	run("cp $src_gff $dir/$gff");
	my $cli = "python3 read-simulator.py $dir/$dna $dir/$gff --double";
	$cli .= ' --coding' unless $opt_x;
	if ($opt_t) {$cli .= " --samplereads 0.1 --samplegenes 0.1"}
	if ($opt_s) {$cli .= " --seed $opt_s"}
	$cli .= " | gzip > $dir/$rna";
	run($cli)
}

# Align

chdir $dir;
foreach my $prog (@program) {
	my $cli = "python3 ../run-aligner.py $dna $rna $prog";
	if ($opt_v) {$cli .= " --verbose"}
	run($cli) if not -s "$prog.ftx.gz";
}

# Compare, Plot, etc
